select
  lo_orderkey,
  lo_linenumber,
  lo_custkey,
  lo_partkey,
  lo_suppkey,
  lo_orderdate,
  lo_orderpriority,
  lo_shippriority,
  lo_quantity,
  lo_extendedprice,
  lo_ordtotalprice,
  lo_discount,
  lo_revenue,
  lo_supplycost,
  lo_tax,
  lo_commitdate,
  lo_shipmode,
  lo_custkey as c_custkey,
  c_name,
  c_address,
  c_city,
  c_nation,
  c_region,
  c_phone,
  c_mktsegment,
  lo_suppkey as s_suppkey,
  s_name,
  s_address,
  s_city,
  s_nation,
  s_region,
  s_phone
from lineorder_flat
where c_nation = s_nation;
